name: Terraform Pull Request Checks

on:
  pull_request:
    branches:
    - main
env:
  TF_VERSION: '1.5.0'

permissions: read-all

jobs:
  terraform:
    name: Terraform Lint, Format, and Validate
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1 # Only the latest commit is needed for the PR checks

    # Step 2: Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Step 3: Initialize Terraform (no remote backend setup)
    - name: Terraform Init
      run: terraform init

    # Step 4: Terraform Format Check
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true

    # This step will only run if the previous step fails and will fail the workflow
    - name: Output Terraform Format Results
      if: steps.fmt.outcome == 'failure'
      run: |
        echo "❌ Terraform files are not formatted."

    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Initialize tflint
      run: tflint --init && tflint --version

    # Step 5: Run TFLint
    - name: Run TFLint
      run: tflint -f compact

    # Step 6: Terraform Validate
    - name: Terraform Validate
      run: terraform validate

    # Step 7: Checkov Security Scan
    - name: Test with Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        skip_check: CKV2_AWS_11,CKV2_AWS_12 # Add checks to skip

    # Step 8: Clean up sensitive data
    - name: Remove Terraform State
      run: rm -rf .terraform/ terraform.tfstate terraform.tfstate.backup

    # Security Check: Check out dependencies and avoid cache files
    - name: Clear Caches
      run: sudo rm -rf ~/.cache/terraform
