name: Terraform Pull Request Checks

on:
  pull_request:
    branches:
    - main
env:
  TF_VERSION: '1.5.0'

jobs:
  terraform:
    name: Terraform Lint, Format, and Validate
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1 # Only the latest commit is needed for the PR checks

    # Step 2: Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Step 3: Initialize Terraform (without backend setup)
    - name: Terraform Init
      run: terraform init -backend=false

    # Step 4: Terraform Format Check
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Output Terraform Format Results
      if: steps.fmt.outcome == 'failure'
      run: |
        echo "❌ Terraform files are not formatted."
        exit 1

    - name: 'Install TFLint'
      run: |
        curl -sLo tflint.zip https://github.com/terraform-linters/tflint/releases/download/v${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip
        unzip tflint.zip -d /usr/local/bin/
        tflint --version

    # Step 6: Terraform Validate
    - name: Terraform Validate
      run: terraform validate

    # Step 6: Checkov Security Scan
    - name: Test with Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        framework: terraform 

    # Step 8: Terraform Plan (Dry Run)
    - name: Terraform Plan
      run: terraform plan -no-color -var-file=dev.tfvars
      continue-on-error: true

    # Optional: Fail if any plan differences are found
    # - name: Check for Drift
    #   if: steps.plan.outcome == 'failure'
    #   run: |
    #     echo "❌ Changes detected in Terraform plan."
    #     exit 1

    # Step 9: Clean up sensitive data
    - name: Remove Terraform State
      run: rm -rf .terraform/ terraform.tfstate terraform.tfstate.backup

    # Security Check: Check out dependencies and avoid cache files
    - name: Clear Caches
      run: sudo rm -rf ~/.cache/terraform

