name: Terraform Pull Request Checks

on:
  pull_request:
    branches:
    - main
env:
  TF_VERSION: '1.5.0'

permissions: read-all

jobs:
  terraform:
    name: Terraform Lint, Format, and Validate
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1 # Only the latest commit is needed for the PR checks

    # Step 2: Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Step 3: Initialize Terraform (no remote backend setup)
    - name: Terraform Init
      run: terraform init

    # Step 4: Terraform Format Check
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: false

    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Initialize tflint
      run: tflint --init && tflint --version

    # Step 5: Run TFLint
    - name: Run TFLint
      run: tflint -f compact

    # Step 6: Terraform Validate
    - name: Terraform Validate
      run: terraform validate

    # Step 7: Checkov Security Scan
    - name: Test with Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        skip_check: CKV2_AWS_11,CKV2_AWS_12,CKV_AWS_24,CKV_AWS_260,CKV_AWS_135,CKV_AWS_79,CKV_AWS_126,CKV_AWS_130,CKV2_AWS_41 # Add checks to skip

    # Step 8: Clean up sensitive data
    - name: Remove Terraform State
      run: rm -rf .terraform/ terraform.tfstate terraform.tfstate.backup

    # Security Check: Check out dependencies and avoid cache files
    - name: Clear Caches
      run: sudo rm -rf ~/.cache/terraform



# Checkov check skips: 
  
# CKV2_AWS_11: Ensure VPC has flow logs enabled (cost)
# CKV2_AWS_12: EBS volume envryption should be enabled (cost)
# CKV_AWS_24: Ensure no security groups allow ingress from 0.0.0.0:0 to port 22 (assignment requirement)
# CKV_AWS_260: Ensure no security groups allow ingress from 0.0.0.0:0 to port 80 (assignment requirement)
# CKV_AWS_135: Ensure that EC2 is EBS optimized (cost)
# CKV_AWS_79: Ensure Instance Metadata Service Version 1 is not enabled
# CKV_AWS_126: Ensure that detailed monitoring is enabled for EC2 instances (cost)
# CKV_AWS_130: Ensure VPC subnets do not assign public IP by default (need to be enabled manually otherwise. For ec2 instance)
# CKV2_AWS_41: Ensure an IAM role is attached to EC2 instance (not needed currently)
